
modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/ate47/CursorMod/issues"
[[mods]]
	modId="customcursormod"
	version="1.2.2"
	displayName="Custom Cursor Mod"
	displayURL="https://minecraft.curseforge.com/projects/cursor-mod"
	authors="ATE47, KevinFernandezDominguez"
	description="Change your cursor."

[[dependencies.customcursormod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
    
